apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming-load-test
  name: streaming-load-test
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: streaming-load-test
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: streaming-load-test
    spec:
      containers:
        - args:
            - --no-web
          env:
            - name: HOST_URL
              value: https://streaming.campusdomar.es
            - name: LOCUST_HEADLESS
              value: "true"
            - name: LOCUST_LOCUSTFILE
              value: /load_generator/locustfiles/vod_dash_hls_sequence.py
            - name: LOCUST_ONLY_SUMMARY
              value: "true"
            - name: LOCUST_RUN_TIME
              value: 600s
            - name: LOCUST_SPAWN_RATE
              value: "1"
            - name: LOCUST_USERS
              value: "1"
            - name: MANIFEST_FILE
              value: live/test/playlist.m3u8
            - name: bitrate
              value: highest_bitrate
            - name: buffer_size
              value: "2"
            - name: mode
              value: live
            - name: play_mode
              value: full_playback
          image: teltek/streaming-load-testing:latest
          name: streaming-load-test
          resources: {}
      restartPolicy: Always
status: {}
